/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 10-Oct.-2019 02:37:33 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS afp_afpid_seq
;

DROP SEQUENCE IF EXISTS conceptos_conceptocodigo_seq
;

DROP SEQUENCE IF EXISTS contratos_contratocodigo_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS AFP CASCADE
;

DROP TABLE IF EXISTS Conceptos CASCADE
;

DROP TABLE IF EXISTS Contratos CASCADE
;

DROP TABLE IF EXISTS Empleados CASCADE
;

DROP TABLE IF EXISTS Pagos CASCADE
;

DROP TABLE IF EXISTS Periodos CASCADE
;

/* Create Tables */

CREATE TABLE AFP
(
	AFPId integer NOT NULL   DEFAULT NEXTVAL(('"afp_afpid_seq"'::text)::regclass),
	AFPDescuento numeric NOT NULL,
	AFPNombre varchar(50) NOT NULL
)
;

CREATE TABLE Conceptos
(
	ConceptoCodigo integer NOT NULL   DEFAULT NEXTVAL(('"conceptos_conceptocodigo_seq"'::text)::regclass),
	montoAdelantado numeric(10,2) NOT NULL,
	montoHoras numeric(10,2) NOT NULL,
	montoHorasAusente numeric(10,2) NOT NULL,
	montoOtrosIngresos numeric(10,2) NOT NULL,
	montoReintegro numeric(10,2) NOT NULL,
	ContratoCodigo integer NULL,
	PeriodoCodigo char(8) NULL
)
;

CREATE TABLE Contratos
(
	ContratoCodigo integer NOT NULL   DEFAULT NEXTVAL(('"contratos_contratocodigo_seq"'::text)::regclass),
	ContratoFechaInicio date NOT NULL,
	ContratoFechaFin date NOT NULL,
	ContratoAsignacionFamiliar char(1) NOT NULL,
	ContratoTotalHorasSemanal integer NOT NULL,
	ContratoValorHoras numeric(10,3) NOT NULL,
	ContratoCargo varchar(50) NOT NULL,
	AFPId integer NULL,
	EmpleadoCodigo char(8) NULL,
	ContratoTipo char(1) NOT NULL DEFAULT 'A',
	PeriodoCodigo char(8) NULL
)
;

CREATE TABLE Empleados
(
	EmpleadoCodigo char(8) NOT NULL,
	EmpleadoNombre varchar(90) NOT NULL,
	EmpleadoDNI char(8) NOT NULL,
	EmpleadoDireccion varchar(150) NOT NULL,
	EmpleadoTelefono integer NOT NULL,
	EmpleadoFechaNacimiento date NOT NULL,
	EmpleadoEstadoCivil char(1) NOT NULL,
	EmpleadoGradoAcademico varchar(50) NOT NULL
)
;

CREATE TABLE Pagos
(
	PagoCodigo char(8) NOT NULL,
	PagoAsignacionFamiliar numeric(10,2) NOT NULL,
	PagoFecha date NOT NULL,
	PagoPorcentajeAFP numeric(10,2) NOT NULL,
	PagoTotalHoras numeric(10,2) NOT NULL,
	PagoValorHoras numeric(10,2) NOT NULL,
	ContratoCodigo integer NULL,
	PeriodoCodigo char(8) NULL,
	ConceptoCodigo integer NULL
)
;

CREATE TABLE Periodos
(
	PeriodoCodigo char(8) NOT NULL,
	PeriodoFechaInicio date NOT NULL,
	PeriodoFechaFin date NOT NULL,
	PeriodoEstado char(1) NOT NULL   DEFAULT 'E'
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE AFP ADD CONSTRAINT AFPCodigoPK
	PRIMARY KEY (AFPId)
;

ALTER TABLE Conceptos ADD CONSTRAINT ConceptoCodigoPK
	PRIMARY KEY (ConceptoCodigo)
;

ALTER TABLE Contratos ADD CONSTRAINT ContratoCodigoPK
	PRIMARY KEY (ContratoCodigo)
;

ALTER TABLE Contratos ADD CONSTRAINT ContratoTipoCK CHECK (ContratoTipo = 'A' or ContratoTipo = 'N')
;

ALTER TABLE Empleados ADD CONSTRAINT EmpleadoCodigoPK
	PRIMARY KEY (EmpleadoCodigo)
;

ALTER TABLE Empleados ADD CONSTRAINT EmpleadoEstadoCivilCK CHECK (EmpleadoEstadoCivil = 'C' or EmpleadoEstadoCivil = 'S' OR EmpleadoEstadoCivil = 'D' OR EmpleadoEstadoCivil = 'V')
;

ALTER TABLE Pagos ADD CONSTRAINT PagoCodigoPK
	PRIMARY KEY (PagoCodigo)
;

ALTER TABLE Periodos ADD CONSTRAINT PeriodoCodigoPK
	PRIMARY KEY (PeriodoCodigo)
;

ALTER TABLE Periodos ADD CONSTRAINT PeriodoEstadoCK CHECK (PeriodoEstado = 'E' or PeriodoEstado = 'D')
;

/* Create Foreign Key Constraints */

ALTER TABLE Conceptos ADD CONSTRAINT ConceptoContratoCodigoFK
	FOREIGN KEY (ContratoCodigo) REFERENCES Contratos (ContratoCodigo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Conceptos ADD CONSTRAINT ConceptoPeriodoCodigoFK
	FOREIGN KEY (PeriodoCodigo) REFERENCES Periodos (PeriodoCodigo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Contratos ADD CONSTRAINT ContratoAFPIdFK
	FOREIGN KEY (AFPId) REFERENCES AFP (AFPId) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Contratos ADD CONSTRAINT ContratoEmpleadoCodigoFK
	FOREIGN KEY (EmpleadoCodigo) REFERENCES Empleados (EmpleadoCodigo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Contratos ADD CONSTRAINT ContratoPeriodoCodigoFK
	FOREIGN KEY (PeriodoCodigo) REFERENCES Periodos (PeriodoCodigo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Pagos ADD CONSTRAINT PagoConceptoCodigoFK
	FOREIGN KEY (ConceptoCodigo) REFERENCES Conceptos (ConceptoCodigo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Pagos ADD CONSTRAINT PagoContratoCodigoFK
	FOREIGN KEY (ContratoCodigo) REFERENCES Contratos (ContratoCodigo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Pagos ADD CONSTRAINT PagoPeriodoCodigoFK
	FOREIGN KEY (PeriodoCodigo) REFERENCES Periodos (PeriodoCodigo) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE afp_afpid_seq INCREMENT 1 START 1
;

CREATE SEQUENCE conceptos_conceptocodigo_seq INCREMENT 1 START 1
;

CREATE SEQUENCE contratos_contratocodigo_seq INCREMENT 1 START 1
;
